"""
Stage 3 — mCRL2 Specification Generator
THIS FILE ONLY WRITES .mcrl2 FILES. IT DOES NOT RUN MCRL2.
Run it with: py mcrl2_gen.py
Expected output: lines starting with 'N=5: wrote...' and 'N=12: wrote...'
"""

import os
from extract_data import (
    load_corridor_trains,
    select_density_subset,
    tag_fastest_as_premium,
)


def normalize_block(s1, s2):
    return "_".join(sorted([s1, s2]))


def blocks_for_train(train):
    stations = [e.station_code for e in train.events]
    return [normalize_block(stations[i], stations[i+1])
            for i in range(len(stations)-1)]


def all_blocks(trains_dict):
    blocks = set()
    for t in trains_dict.values():
        for b in blocks_for_train(t):
            blocks.add(b)
    return sorted(blocks)


def safe(tno):
    return str(tno).replace("-", "_").replace(".", "_")


def generate_mcrl2_spec(trains_dict, out_path="snapshot.mcrl2"):
    """Write a real mCRL2 process specification to out_path.
    Returns the path written."""
    blocks    = all_blocks(trains_dict)
    train_ids = list(trains_dict.keys())
    L = []

    L.append(f"% mCRL2 snapshot -- {len(train_ids)} trains, {len(blocks)} blocks")
    L.append(f"% Generated by OVR framework Stage 3")
    L.append("")

    # Observable actions: enter/leave per train per block
    enter_leave = []
    for tno in train_ids:
        sid = safe(tno)
        for b in blocks_for_train(trains_dict[tno]):
            enter_leave.append(f"enter_{sid}_{b}")
            enter_leave.append(f"leave_{sid}_{b}")

    # Sync actions: req/grant/rel/free per block
    sync_acts = []
    for b in blocks:
        sync_acts += [f"req_{b}", f"grant_{b}",
                      f"rel_{b}", f"free_{b}",
                      f"sync_req_{b}", f"sync_rel_{b}"]

    # Write action declarations
    all_acts = enter_leave + sync_acts
    L.append("act")
    for i, a in enumerate(all_acts):
        suffix = "," if i < len(all_acts)-1 else ";"
        L.append(f"  {a}{suffix}")
    L.append("")

    # Train processes
    L.append("% Train processes")
    for tno in train_ids:
        sid  = safe(tno)
        bseq = blocks_for_train(trains_dict[tno])
        steps = []
        for b in bseq:
            steps.append(
                f"enter_{sid}_{b} . req_{b} . grant_{b} . "
                f"leave_{sid}_{b} . rel_{b} . free_{b}"
            )
        body = " .\n    ".join(steps)
        L.append(f"proc Train_{sid} =")
        L.append(f"  {body};")
        L.append("")

    # Block semaphore processes
    L.append("% Block semaphore processes")
    for b in blocks:
        L.append(f"proc Block_{b} =")
        L.append(f"  sync_req_{b} . sync_rel_{b} . Block_{b};")
        L.append("")

    # Communication map
    comm_list = []
    for b in blocks:
        comm_list.append(f"req_{b} | sync_req_{b} -> grant_{b}")
        comm_list.append(f"rel_{b} | sync_rel_{b} -> free_{b}")
    comm_str = ",\n    ".join(comm_list)

    # Allow set
    allow_list = (enter_leave +
                  [f"grant_{b}" for b in blocks] +
                  [f"free_{b}"  for b in blocks])
    allow_str = ", ".join(allow_list)

    # System init
    train_procs = " || ".join(f"Train_{safe(tno)}" for tno in train_ids)
    block_procs = " || ".join(f"Block_{b}" for b in blocks)

    L.append("% System composition")
    L.append("init")
    L.append(f"  allow({{ {allow_str} }},")
    L.append(f"    comm({{ {comm_str} }},")
    L.append(f"      {train_procs} || {block_procs}")
    L.append("    ));")

    spec = "\n".join(L)
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(spec)
    return out_path


if __name__ == "__main__":
    print("=== mcrl2_gen.py: GENERATING SPEC FILES ONLY (not running mCRL2) ===")
    trains = load_corridor_trains()

    for n in [5, 12]:
        subset = select_density_subset(trains, n)
        tag_fastest_as_premium(subset)
        path = generate_mcrl2_spec(subset, out_path=f"snapshot_n{n}.mcrl2")
        print(f"N={n}: wrote {path}")
        with open(path) as f:
            content = f.read()
        lines = content.strip().split("\n")
        print(f"  Lines: {len(lines)}")
        print(f"  Last 3 lines of spec:")
        for line in lines[-3:]:
            print(f"    {line}")
        print()

    print("DONE. Now run: py run_mcrl2.py")